version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    container_name: 'mysql_twclientes'
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: twclientes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  db_data: { }
  api-logs: